# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x86'
- task: PowerShell@2
  name: InsertSecrets
  inputs:
    targetType: 'inline'
    script: |
      (Get-Content installer.py).replace('{{PROD_API_URL}}', ${env:API_URL}) | Set-Content installer.py
      (Get-Content installer.py).replace('{{PROD_APP_ID}}', ${env:APP_ID}) | Set-Content installer.py
      (Get-Content installer.py).replace('{{PROD_TOKEN_URL}}', ${env:TOKEN_URL}) | Set-Content installer.py
      (Get-Content installer.py).replace('{{PROD_AUTHORIZATION_URL}}', ${env:AUTHORIZATION_URL}) | Set-Content installer.py
- task: CmdLine@2
  inputs:
    script: |
      cat installer.py
- task: CmdLine@2
  inputs:
    script: 'pip install pyinstaller'
- task: CmdLine@2
  inputs:
    script: |
      pyinstaller --distpath $(Build.ArtifactStagingDirectory) --onefile --windowed installer.py
      pyinstaller --distpath $(Build.ArtifactStagingDirectory) --onefile --windowed start.py
      pyinstaller --distpath $(Build.ArtifactStagingDirectory) --onefile --windowed stop.py
      dir dist
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'bin'
    publishLocation: 'Container'
