# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x86'
- task: CmdLine@2
  inputs:
    script: |
      sed -i -e 's/{{PROD_API_URL}}/%API_URL%/g' installer.py
      sed -i -e 's/{{PROD_APP_ID}}/%APP_ID%/g' installer.py
      sed -i -e 's/{{PROD_TOKEN_URL}}/%TOKEN_URL%/g' installer.py
      sed -i -e 's/{{PROD_AUTHORIZATION_URL}}/%AUTHORIZATION_URL%/g' installer.py
      cat installer.py
- task: CmdLine@2
  inputs:
    script: 'pip install pyinstaller'
- task: CmdLine@2
  inputs:
    script: |
      pyinstaller --onefile --windowed installer.py
      pyinstaller --onefile --windowed start.py
      pyinstaller --onefile --windowed stop.py
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'bin'
    publishLocation: 'Container'
